site_name: DeepFlow Docs

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
            show_signature: false
            show_root_heading: true
            heading_level: 2
            show_category_heading: true
            show_if_no_docstring: false
            show_if_no_signature: false
            show_if_no_return_annotation: false

theme:
  name: mkdocs
  language: zh_cn
  palette:
    primary: 'blue'
    accent: 'blue'
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - navigation.instant
    - navigation.tabs.sticky
    - navigation.tabs.sticky_plus_subheader
